// Generated by gencpp from file il_map_tools/Pan_tilt.msg
// DO NOT EDIT!


#ifndef IL_MAP_TOOLS_MESSAGE_PAN_TILT_H
#define IL_MAP_TOOLS_MESSAGE_PAN_TILT_H

#include <ros/service_traits.h>


#include <il_map_tools/Pan_tiltRequest.h>
#include <il_map_tools/Pan_tiltResponse.h>


namespace il_map_tools
{

struct Pan_tilt
{

typedef Pan_tiltRequest Request;
typedef Pan_tiltResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Pan_tilt
} // namespace il_map_tools


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::il_map_tools::Pan_tilt > {
  static const char* value()
  {
    return "8758be18bed045a5f20b257314365f33";
  }

  static const char* value(const ::il_map_tools::Pan_tilt&) { return value(); }
};

template<>
struct DataType< ::il_map_tools::Pan_tilt > {
  static const char* value()
  {
    return "il_map_tools/Pan_tilt";
  }

  static const char* value(const ::il_map_tools::Pan_tilt&) { return value(); }
};


// service_traits::MD5Sum< ::il_map_tools::Pan_tiltRequest> should match 
// service_traits::MD5Sum< ::il_map_tools::Pan_tilt > 
template<>
struct MD5Sum< ::il_map_tools::Pan_tiltRequest>
{
  static const char* value()
  {
    return MD5Sum< ::il_map_tools::Pan_tilt >::value();
  }
  static const char* value(const ::il_map_tools::Pan_tiltRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::il_map_tools::Pan_tiltRequest> should match 
// service_traits::DataType< ::il_map_tools::Pan_tilt > 
template<>
struct DataType< ::il_map_tools::Pan_tiltRequest>
{
  static const char* value()
  {
    return DataType< ::il_map_tools::Pan_tilt >::value();
  }
  static const char* value(const ::il_map_tools::Pan_tiltRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::il_map_tools::Pan_tiltResponse> should match 
// service_traits::MD5Sum< ::il_map_tools::Pan_tilt > 
template<>
struct MD5Sum< ::il_map_tools::Pan_tiltResponse>
{
  static const char* value()
  {
    return MD5Sum< ::il_map_tools::Pan_tilt >::value();
  }
  static const char* value(const ::il_map_tools::Pan_tiltResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::il_map_tools::Pan_tiltResponse> should match 
// service_traits::DataType< ::il_map_tools::Pan_tilt > 
template<>
struct DataType< ::il_map_tools::Pan_tiltResponse>
{
  static const char* value()
  {
    return DataType< ::il_map_tools::Pan_tilt >::value();
  }
  static const char* value(const ::il_map_tools::Pan_tiltResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IL_MAP_TOOLS_MESSAGE_PAN_TILT_H
