// Generated by gencpp from file il_map_tools/srv_occupied.msg
// DO NOT EDIT!


#ifndef IL_MAP_TOOLS_MESSAGE_SRV_OCCUPIED_H
#define IL_MAP_TOOLS_MESSAGE_SRV_OCCUPIED_H

#include <ros/service_traits.h>


#include <il_map_tools/srv_occupiedRequest.h>
#include <il_map_tools/srv_occupiedResponse.h>


namespace il_map_tools
{

struct srv_occupied
{

typedef srv_occupiedRequest Request;
typedef srv_occupiedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srv_occupied
} // namespace il_map_tools


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::il_map_tools::srv_occupied > {
  static const char* value()
  {
    return "5c8af5f97a4667b1e2ca25d4017d3de1";
  }

  static const char* value(const ::il_map_tools::srv_occupied&) { return value(); }
};

template<>
struct DataType< ::il_map_tools::srv_occupied > {
  static const char* value()
  {
    return "il_map_tools/srv_occupied";
  }

  static const char* value(const ::il_map_tools::srv_occupied&) { return value(); }
};


// service_traits::MD5Sum< ::il_map_tools::srv_occupiedRequest> should match 
// service_traits::MD5Sum< ::il_map_tools::srv_occupied > 
template<>
struct MD5Sum< ::il_map_tools::srv_occupiedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::il_map_tools::srv_occupied >::value();
  }
  static const char* value(const ::il_map_tools::srv_occupiedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::il_map_tools::srv_occupiedRequest> should match 
// service_traits::DataType< ::il_map_tools::srv_occupied > 
template<>
struct DataType< ::il_map_tools::srv_occupiedRequest>
{
  static const char* value()
  {
    return DataType< ::il_map_tools::srv_occupied >::value();
  }
  static const char* value(const ::il_map_tools::srv_occupiedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::il_map_tools::srv_occupiedResponse> should match 
// service_traits::MD5Sum< ::il_map_tools::srv_occupied > 
template<>
struct MD5Sum< ::il_map_tools::srv_occupiedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::il_map_tools::srv_occupied >::value();
  }
  static const char* value(const ::il_map_tools::srv_occupiedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::il_map_tools::srv_occupiedResponse> should match 
// service_traits::DataType< ::il_map_tools::srv_occupied > 
template<>
struct DataType< ::il_map_tools::srv_occupiedResponse>
{
  static const char* value()
  {
    return DataType< ::il_map_tools::srv_occupied >::value();
  }
  static const char* value(const ::il_map_tools::srv_occupiedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IL_MAP_TOOLS_MESSAGE_SRV_OCCUPIED_H
