// Generated by gencpp from file il_map_tools/srv_occupiedResponse.msg
// DO NOT EDIT!


#ifndef IL_MAP_TOOLS_MESSAGE_SRV_OCCUPIEDRESPONSE_H
#define IL_MAP_TOOLS_MESSAGE_SRV_OCCUPIEDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace il_map_tools
{
template <class ContainerAllocator>
struct srv_occupiedResponse_
{
  typedef srv_occupiedResponse_<ContainerAllocator> Type;

  srv_occupiedResponse_()
    : occupied(0)  {
    }
  srv_occupiedResponse_(const ContainerAllocator& _alloc)
    : occupied(0)  {
    }



   typedef uint8_t _occupied_type;
  _occupied_type occupied;




  typedef boost::shared_ptr< ::il_map_tools::srv_occupiedResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::il_map_tools::srv_occupiedResponse_<ContainerAllocator> const> ConstPtr;

}; // struct srv_occupiedResponse_

typedef ::il_map_tools::srv_occupiedResponse_<std::allocator<void> > srv_occupiedResponse;

typedef boost::shared_ptr< ::il_map_tools::srv_occupiedResponse > srv_occupiedResponsePtr;
typedef boost::shared_ptr< ::il_map_tools::srv_occupiedResponse const> srv_occupiedResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::il_map_tools::srv_occupiedResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::il_map_tools::srv_occupiedResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace il_map_tools

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::il_map_tools::srv_occupiedResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::il_map_tools::srv_occupiedResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::il_map_tools::srv_occupiedResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::il_map_tools::srv_occupiedResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::il_map_tools::srv_occupiedResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::il_map_tools::srv_occupiedResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::il_map_tools::srv_occupiedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "78750e2e6a6a8f1a92e5408a205df907";
  }

  static const char* value(const ::il_map_tools::srv_occupiedResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x78750e2e6a6a8f1aULL;
  static const uint64_t static_value2 = 0x92e5408a205df907ULL;
};

template<class ContainerAllocator>
struct DataType< ::il_map_tools::srv_occupiedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "il_map_tools/srv_occupiedResponse";
  }

  static const char* value(const ::il_map_tools::srv_occupiedResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::il_map_tools::srv_occupiedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 occupied\n\
\n\
";
  }

  static const char* value(const ::il_map_tools::srv_occupiedResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::il_map_tools::srv_occupiedResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.occupied);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct srv_occupiedResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::il_map_tools::srv_occupiedResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::il_map_tools::srv_occupiedResponse_<ContainerAllocator>& v)
  {
    s << indent << "occupied: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.occupied);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IL_MAP_TOOLS_MESSAGE_SRV_OCCUPIEDRESPONSE_H
