// Generated by gencpp from file messages/Camino.msg
// DO NOT EDIT!


#ifndef MESSAGES_MESSAGE_CAMINO_H
#define MESSAGES_MESSAGE_CAMINO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <messages/Punto.h>

namespace messages
{
template <class ContainerAllocator>
struct Camino_
{
  typedef Camino_<ContainerAllocator> Type;

  Camino_()
    : header()
    , puntos()  {
    }
  Camino_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , puntos(_alloc)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::messages::Punto_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::messages::Punto_<ContainerAllocator> >::other >  _puntos_type;
  _puntos_type puntos;




  typedef boost::shared_ptr< ::messages::Camino_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::messages::Camino_<ContainerAllocator> const> ConstPtr;

}; // struct Camino_

typedef ::messages::Camino_<std::allocator<void> > Camino;

typedef boost::shared_ptr< ::messages::Camino > CaminoPtr;
typedef boost::shared_ptr< ::messages::Camino const> CaminoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::messages::Camino_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::messages::Camino_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace messages

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'messages': ['/home/champion/catkin_ws/src/messages/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::messages::Camino_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::messages::Camino_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messages::Camino_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messages::Camino_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages::Camino_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages::Camino_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::messages::Camino_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a18639cc1614ee5059ad5ac8d18d4085";
  }

  static const char* value(const ::messages::Camino_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa18639cc1614ee50ULL;
  static const uint64_t static_value2 = 0x59ad5ac8d18d4085ULL;
};

template<class ContainerAllocator>
struct DataType< ::messages::Camino_<ContainerAllocator> >
{
  static const char* value()
  {
    return "messages/Camino";
  }

  static const char* value(const ::messages::Camino_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::messages::Camino_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
Punto[] puntos\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: messages/Punto\n\
Header header\n\
float64 x\n\
float64 y\n\
float64 angulo_pan\n\
float64 angulo_tilt\n\
float64 tiempo\n\
";
  }

  static const char* value(const ::messages::Camino_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::messages::Camino_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.puntos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Camino_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::messages::Camino_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::messages::Camino_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "puntos[]" << std::endl;
    for (size_t i = 0; i < v.puntos.size(); ++i)
    {
      s << indent << "  puntos[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::messages::Punto_<ContainerAllocator> >::stream(s, indent + "    ", v.puntos[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGES_MESSAGE_CAMINO_H
