// Generated by gencpp from file messages/Pan_tilt_mess.msg
// DO NOT EDIT!


#ifndef MESSAGES_MESSAGE_PAN_TILT_MESS_H
#define MESSAGES_MESSAGE_PAN_TILT_MESS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace messages
{
template <class ContainerAllocator>
struct Pan_tilt_mess_
{
  typedef Pan_tilt_mess_<ContainerAllocator> Type;

  Pan_tilt_mess_()
    : header()
    , pan(0.0)
    , tilt(0.0)  {
    }
  Pan_tilt_mess_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pan(0.0)
    , tilt(0.0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _pan_type;
  _pan_type pan;

   typedef double _tilt_type;
  _tilt_type tilt;




  typedef boost::shared_ptr< ::messages::Pan_tilt_mess_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::messages::Pan_tilt_mess_<ContainerAllocator> const> ConstPtr;

}; // struct Pan_tilt_mess_

typedef ::messages::Pan_tilt_mess_<std::allocator<void> > Pan_tilt_mess;

typedef boost::shared_ptr< ::messages::Pan_tilt_mess > Pan_tilt_messPtr;
typedef boost::shared_ptr< ::messages::Pan_tilt_mess const> Pan_tilt_messConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::messages::Pan_tilt_mess_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::messages::Pan_tilt_mess_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace messages

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'messages': ['/home/champion/catkin_ws/src/messages/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::messages::Pan_tilt_mess_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::messages::Pan_tilt_mess_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messages::Pan_tilt_mess_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messages::Pan_tilt_mess_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages::Pan_tilt_mess_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages::Pan_tilt_mess_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::messages::Pan_tilt_mess_<ContainerAllocator> >
{
  static const char* value()
  {
    return "919b8e9b18fec5e324500406fde49f2b";
  }

  static const char* value(const ::messages::Pan_tilt_mess_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x919b8e9b18fec5e3ULL;
  static const uint64_t static_value2 = 0x24500406fde49f2bULL;
};

template<class ContainerAllocator>
struct DataType< ::messages::Pan_tilt_mess_<ContainerAllocator> >
{
  static const char* value()
  {
    return "messages/Pan_tilt_mess";
  }

  static const char* value(const ::messages::Pan_tilt_mess_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::messages::Pan_tilt_mess_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float64 pan\n\
float64 tilt\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::messages::Pan_tilt_mess_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::messages::Pan_tilt_mess_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pan);
      stream.next(m.tilt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Pan_tilt_mess_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::messages::Pan_tilt_mess_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::messages::Pan_tilt_mess_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pan: ";
    Printer<double>::stream(s, indent + "  ", v.pan);
    s << indent << "tilt: ";
    Printer<double>::stream(s, indent + "  ", v.tilt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGES_MESSAGE_PAN_TILT_MESS_H
