// Generated by gencpp from file messages/Pan_tiltResponse.msg
// DO NOT EDIT!


#ifndef MESSAGES_MESSAGE_PAN_TILTRESPONSE_H
#define MESSAGES_MESSAGE_PAN_TILTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace messages
{
template <class ContainerAllocator>
struct Pan_tiltResponse_
{
  typedef Pan_tiltResponse_<ContainerAllocator> Type;

  Pan_tiltResponse_()
    : pan(0.0)
    , tilt(0.0)  {
    }
  Pan_tiltResponse_(const ContainerAllocator& _alloc)
    : pan(0.0)
    , tilt(0.0)  {
    }



   typedef double _pan_type;
  _pan_type pan;

   typedef double _tilt_type;
  _tilt_type tilt;




  typedef boost::shared_ptr< ::messages::Pan_tiltResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::messages::Pan_tiltResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Pan_tiltResponse_

typedef ::messages::Pan_tiltResponse_<std::allocator<void> > Pan_tiltResponse;

typedef boost::shared_ptr< ::messages::Pan_tiltResponse > Pan_tiltResponsePtr;
typedef boost::shared_ptr< ::messages::Pan_tiltResponse const> Pan_tiltResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::messages::Pan_tiltResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::messages::Pan_tiltResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace messages

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'messages': ['/home/champion/catkin_ws/src/messages/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::messages::Pan_tiltResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::messages::Pan_tiltResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messages::Pan_tiltResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messages::Pan_tiltResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages::Pan_tiltResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages::Pan_tiltResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::messages::Pan_tiltResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da61f3d6b381bd4af7a066f22fdfa441";
  }

  static const char* value(const ::messages::Pan_tiltResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda61f3d6b381bd4aULL;
  static const uint64_t static_value2 = 0xf7a066f22fdfa441ULL;
};

template<class ContainerAllocator>
struct DataType< ::messages::Pan_tiltResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "messages/Pan_tiltResponse";
  }

  static const char* value(const ::messages::Pan_tiltResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::messages::Pan_tiltResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 pan\n\
float64 tilt\n\
";
  }

  static const char* value(const ::messages::Pan_tiltResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::messages::Pan_tiltResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pan);
      stream.next(m.tilt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Pan_tiltResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::messages::Pan_tiltResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::messages::Pan_tiltResponse_<ContainerAllocator>& v)
  {
    s << indent << "pan: ";
    Printer<double>::stream(s, indent + "  ", v.pan);
    s << indent << "tilt: ";
    Printer<double>::stream(s, indent + "  ", v.tilt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGES_MESSAGE_PAN_TILTRESPONSE_H
