// Generated by gencpp from file messages/Pan_tilt.msg
// DO NOT EDIT!


#ifndef MESSAGES_MESSAGE_PAN_TILT_H
#define MESSAGES_MESSAGE_PAN_TILT_H

#include <ros/service_traits.h>


#include <messages/Pan_tiltRequest.h>
#include <messages/Pan_tiltResponse.h>


namespace messages
{

struct Pan_tilt
{

typedef Pan_tiltRequest Request;
typedef Pan_tiltResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Pan_tilt
} // namespace messages


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::messages::Pan_tilt > {
  static const char* value()
  {
    return "da61f3d6b381bd4af7a066f22fdfa441";
  }

  static const char* value(const ::messages::Pan_tilt&) { return value(); }
};

template<>
struct DataType< ::messages::Pan_tilt > {
  static const char* value()
  {
    return "messages/Pan_tilt";
  }

  static const char* value(const ::messages::Pan_tilt&) { return value(); }
};


// service_traits::MD5Sum< ::messages::Pan_tiltRequest> should match 
// service_traits::MD5Sum< ::messages::Pan_tilt > 
template<>
struct MD5Sum< ::messages::Pan_tiltRequest>
{
  static const char* value()
  {
    return MD5Sum< ::messages::Pan_tilt >::value();
  }
  static const char* value(const ::messages::Pan_tiltRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::messages::Pan_tiltRequest> should match 
// service_traits::DataType< ::messages::Pan_tilt > 
template<>
struct DataType< ::messages::Pan_tiltRequest>
{
  static const char* value()
  {
    return DataType< ::messages::Pan_tilt >::value();
  }
  static const char* value(const ::messages::Pan_tiltRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::messages::Pan_tiltResponse> should match 
// service_traits::MD5Sum< ::messages::Pan_tilt > 
template<>
struct MD5Sum< ::messages::Pan_tiltResponse>
{
  static const char* value()
  {
    return MD5Sum< ::messages::Pan_tilt >::value();
  }
  static const char* value(const ::messages::Pan_tiltResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::messages::Pan_tiltResponse> should match 
// service_traits::DataType< ::messages::Pan_tilt > 
template<>
struct DataType< ::messages::Pan_tiltResponse>
{
  static const char* value()
  {
    return DataType< ::messages::Pan_tilt >::value();
  }
  static const char* value(const ::messages::Pan_tiltResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MESSAGES_MESSAGE_PAN_TILT_H
