// Generated by gencpp from file messages/Pan_tiltRequest.msg
// DO NOT EDIT!


#ifndef MESSAGES_MESSAGE_PAN_TILTREQUEST_H
#define MESSAGES_MESSAGE_PAN_TILTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace messages
{
template <class ContainerAllocator>
struct Pan_tiltRequest_
{
  typedef Pan_tiltRequest_<ContainerAllocator> Type;

  Pan_tiltRequest_()
    {
    }
  Pan_tiltRequest_(const ContainerAllocator& _alloc)
    {
    }






  typedef boost::shared_ptr< ::messages::Pan_tiltRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::messages::Pan_tiltRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Pan_tiltRequest_

typedef ::messages::Pan_tiltRequest_<std::allocator<void> > Pan_tiltRequest;

typedef boost::shared_ptr< ::messages::Pan_tiltRequest > Pan_tiltRequestPtr;
typedef boost::shared_ptr< ::messages::Pan_tiltRequest const> Pan_tiltRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::messages::Pan_tiltRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::messages::Pan_tiltRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace messages

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'messages': ['/home/champion/catkin_ws/src/messages/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::messages::Pan_tiltRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::messages::Pan_tiltRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messages::Pan_tiltRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messages::Pan_tiltRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages::Pan_tiltRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages::Pan_tiltRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::messages::Pan_tiltRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::messages::Pan_tiltRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::messages::Pan_tiltRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "messages/Pan_tiltRequest";
  }

  static const char* value(const ::messages::Pan_tiltRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::messages::Pan_tiltRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::messages::Pan_tiltRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::messages::Pan_tiltRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Pan_tiltRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::messages::Pan_tiltRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::messages::Pan_tiltRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGES_MESSAGE_PAN_TILTREQUEST_H
